name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Clone source repository
        run: |
          git clone \
          --recursive \
          --single-branch \
          --branch winlator_bionic \
          https://github.com/Pipetto-crypto/winlator

      - name: Checkout build repository
        uses: actions/checkout@v4
        with:
          path: build

      - name: Get current source commit SHA and changelog
        run: |
          cd winlator
          if [ -f ../build/commit_sha.txt ]; then
            echo "CHANGELOG=$(git log --pretty=format:%s $(cat ../build/commit_sha.txt)..HEAD)" >> $GITHUB_ENV
            git rev-parse HEAD > ../build/commit_sha.txt
          else
            git rev-parse HEAD > ../build/commit_sha.txt
            echo "CHANGELOG=$(git log --pretty=format:%s $(cat ../build/commit_sha.txt)..HEAD)" >> $GITHUB_ENV
          fi

      - name: Update last build commit SHA
        run: |
          cd build
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add commit_sha.txt
          git commit -m "Update last build commit SHA" || true
          git push
          
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set gradlew permissions
        run: |
          cd winlator
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd winlator
          ./gradlew assembleDebug

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.CHANGELOG }}
          files: winlator/app/build/outputs/apk/debug/app-debug.apk
          name: winlator-bionic-${{ env.DATE }}
          tag_name: ${{ env.DATE }}
